# Generated by Django 3.1.7 on 2021-02-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210224_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Author Uknown', max_length=200, null=True),
        ),
    ]
